/** General editorial vocabulary, never article-specific factual substitutions. Longest matches win. */
export const GLOSSARY: Record<string, { en: string; roman: string }> = {
  "नरेंद्र मोदी": { en: "Narendra Modi", roman: "Narendra Modi" },
  "नई दिल्ली": { en: "New Delhi", roman: "New Delhi" },
  प्रधानमंत्री: { en: "Prime Minister", roman: "Pradhanmantri" },
  भारत: { en: "India", roman: "Bharat" },
  सरकार: { en: "government", roman: "sarkar" },
  दिल्ली: { en: "Delhi", roman: "Delhi" },
  जनवरी: { en: "January", roman: "January" },
  फरवरी: { en: "February", roman: "February" },
  मार्च: { en: "March", roman: "March" },
  अप्रैल: { en: "April", roman: "April" },
  मई: { en: "May", roman: "May" },
  जून: { en: "June", roman: "June" },
  जुलाई: { en: "July", roman: "July" },
  अगस्त: { en: "August", roman: "August" },
  सितंबर: { en: "September", roman: "September" },
  सितम्बर: { en: "September", roman: "September" },
  अक्टूबर: { en: "October", roman: "October" },
  नवंबर: { en: "November", roman: "November" },
  नवम्बर: { en: "November", roman: "November" },
  दिसंबर: { en: "December", roman: "December" },
  करोड़: { en: "crore", roman: "crore" },
  करोड़: { en: "crore", roman: "crore" },
  लाख: { en: "lakh", roman: "lakh" },
  रुपये: { en: "rupees", roman: "rupaye" },
  रुपए: { en: "rupees", roman: "rupaye" },
  डॉलर: { en: "dollars", roman: "dollar" },
  अक्तूबर: { en: "October", roman: "October" },
  शून्य: { en: "zero", roman: "shoonya" },
  एक: { en: "one", roman: "ek" },
  दो: { en: "two", roman: "do" },
  तीन: { en: "three", roman: "teen" },
  चार: { en: "four", roman: "chaar" },
  पांच: { en: "five", roman: "paanch" },
  पाँच: { en: "five", roman: "paanch" },
  छह: { en: "six", roman: "chhah" },
  सात: { en: "seven", roman: "saat" },
  आठ: { en: "eight", roman: "aath" },
  नौ: { en: "nine", roman: "nau" },
  दस: { en: "ten", roman: "das" },
  ग्यारह: { en: "eleven", roman: "gyaarah" },
  बारह: { en: "twelve", roman: "baarah" },
  तेरह: { en: "thirteen", roman: "terah" },
  चौदह: { en: "fourteen", roman: "chaudah" },
  पंद्रह: { en: "fifteen", roman: "pandrah" },
  सोलह: { en: "sixteen", roman: "solah" },
  सत्रह: { en: "seventeen", roman: "satrah" },
  अठारह: { en: "eighteen", roman: "athaarah" },
  उन्नीस: { en: "nineteen", roman: "unnees" },
  बीस: { en: "twenty", roman: "bees" },
  पच्चीस: { en: "twenty-five", roman: "pachchees" },
  तीस: { en: "thirty", roman: "tees" },
  चालीस: { en: "forty", roman: "chaalees" },
  पचास: { en: "fifty", roman: "pachaas" },
  साठ: { en: "sixty", roman: "saath" },
  सत्तर: { en: "seventy", roman: "sattar" },
  अस्सी: { en: "eighty", roman: "assi" },
  नब्बे: { en: "ninety", roman: "nabbe" },
  सौ: { en: "hundred", roman: "sau" },
  हजार: { en: "thousand", roman: "hazaar" },
  हज़ार: { en: "thousand", roman: "hazaar" },
};
